name: thejoker-paper

channels:
  - astropy

dependencies:
  - python=3
  - astropy
  - numpy
  - matplotlib
  - scipy
  - h5py
  - pip:
    - emcee
    - corner
    - git+https://github.com/adrn/thejoker
    - git+https://github.com/adrn/schwimmbad
